"""empty message

Revision ID: bb368a0900a0
Revises: 6ee37c6734c5
Create Date: 2018-08-29 07:09:52.035900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb368a0900a0'
down_revision = '6ee37c6734c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    # ### end Alembic commands ###
